title: Andrés Iniesta
description: Una web homenaje a uno de los jugadores más grandes de la historia del fútbol.
theme: just-the-docs
color_scheme: dark

search_enabled: false

logo: "assets/images/iniesto.jpg"

url: https://Angryel.github.io

aux_links:
  **¡Iniesta de mi vida!**: https://www.youtube.com/watch?v=6-EqlQMPmDI{:target="_blank"}
