title: Andrés Iniesta
description: Una web homenaje a uno de los jugadores mas grandes de la historia del futbol.
theme: just-the-docs
color_scheme: dark

logo: "images/iniesta.png"
favicon_icon: "images/iniesta.png"

url: https://Angryel.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
