title: Andrés Iniesta
description: Una web homenaje a uno de los jugadores más grandes de la historia del fútbol.
theme: just-the-docs
color_scheme: dark

search_enabled: false

logo: "assets/images/iniesto.jpg"

url: https://Angryel.github.io

menu:
  main:
    - title: "Don Andrés"
      url: /index/
    - title: "Barcelona y España"
      url: /futbol/
      submenu:
        - title: "F.C. Barcelona"
          url: /FCB/
        - title: "Proyecto 2"
          url: /SeleccionEspañola/


aux_links:
  ¡Iniesta de mi vida!: https://www.youtube.com/watch?v=6-EqlQMPmDI
