title: Andrés Iniesta
description: Una web homenaje a uno de los jugadores más grandes de la historia del fútbol.
theme: just-the-docs
color_scheme: dark

search_enabled: false

logo: "assets/images/iniesto.jpg"

favicon_ico: "/assets/images/icono.ico"

url: https://Angryel.github.io


aux_links:
  ¡Iniesta de mi vida!: https://www.youtube.com/watch?v=6-EqlQMPmDI

nav_external_links:
  - title: En el Top 3 de Españoles queridos por Inglaterra.
    url: https://www.youtube.com/watch?v=zWBKP-DZNEc
    hide_icon: false 
    opens_in_new_tab: true 
