title: Andrés Iniesta
description: Una web homenaje a uno de los jugadores más grandes de la historia del fútbol.
theme: just-the-docs
color_scheme: dark

favicon_ico: "images/cabecera.ico"
logo: "images/cabecera.png"

url: https://Angryel.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
